python3 -c 'import os
from stat import *

try:
    os.chdir("mnt")
except Exception as e:
    print(e)
    exit(1)

try:
    os.mkdir("d1")
except Exception as e:
    print(e)
    exit(1)

try:
    S_ISDIR(os.stat("d1").st_mode)
except Exception as e:
    print(e)
    exit(1)

try:
    os.mkdir("d2")
except Exception as e:
    print(e)
    exit(1)

try:
    S_ISDIR(os.stat("d2").st_mode)
except Exception as e:
    print(e)
    exit(1)

try:
    os.mkdir("d2/d3")
except Exception as e:
    print(e)
    exit(1)

try:
    S_ISDIR(os.stat("d2/d3").st_mode)
except Exception as e:
    print(e)
    exit(1)

print("Correct")' \
 && fusermount -u mnt && ./wfs-check-metadata.py --mode raid0 --blocks 2 --altblocks 2 --dirs 4 --files 0 --disks /tmp/$(whoami)/test-disk1 /tmp/$(whoami)/test-disk2 /tmp/$(whoami)/test-disk3
