python3 -c 'import os
from stat import *

try:
    os.chdir("mnt")
except Exception as e:
    print(e)
    exit(1)

try:
    os.mknod("file4")
except Exception as e:
    print(e)
    exit(1)

try:
    S_ISREG(os.stat("file4").st_mode)
except Exception as e:
    print(e)
    exit(1)

try:
    os.mknod("file3")
except Exception as e:
    print(e)
    exit(1)

try:
    S_ISREG(os.stat("file3").st_mode)
except Exception as e:
    print(e)
    exit(1)

try:
    os.mknod("file2")
except Exception as e:
    print(e)
    exit(1)

try:
    S_ISREG(os.stat("file2").st_mode)
except Exception as e:
    print(e)
    exit(1)

try:
    os.mknod("file1")
except Exception as e:
    print(e)
    exit(1)

try:
    S_ISREG(os.stat("file1").st_mode)
except Exception as e:
    print(e)
    exit(1)

print("Correct")' \
 && ./readdir-check.py 4 && fusermount -u mnt && ./wfs-check-metadata.py --mode raid1 --blocks 1 --altblocks 1 --dirs 1 --files 4 --disks /tmp/$(whoami)/test-disk1 /tmp/$(whoami)/test-disk2
