python3 -c 'import os
from stat import *

try:
    os.chdir("mnt")
except Exception as e:
    print(e)
    exit(1)

print("Correct")' \
 && ./read-write.py 1 50; cat mnt/file1 > file1.test; fusermount -u mnt; ../solution/wfs /tmp/$(whoami)/test-disk3 /tmp/$(whoami)/test-disk2 /tmp/$(whoami)/test-disk1 -s mnt; diff mnt/file1 file1.test && fusermount -u mnt && ./wfs-check-metadata.py --mode raid0 --blocks 12 --altblocks 14 --dirs 1 --files 1 --disks /tmp/$(whoami)/test-disk1 /tmp/$(whoami)/test-disk2 /tmp/$(whoami)/test-disk3
